=== lalimary/Lab-4/lab3.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">

  <xs:element name="admin">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="library">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="b1" maxOccurs="unbounded">
                  <xs:complexType>
                    <xs:sequence>
                      <xs:element name = "name" type = "xs:string"/>
                      <xs:element name = "author" type = "xs:string"/>
                      <xs:element name = "price" type = "xs:integer"/>
                      <xs:element name = "pages" type = "xs:integer"/>
                      <xs:element name = "genre" type = "xs:string"/>
                      <xs:element name = "publisher" type = "xs:string"/>
                      <xs:element name = "rating">
                        <xs:simpleType>
                        <xs:restriction base="xs:decimal">
                          <xs:minInclusive value="1"/>
                          <xs:maxInclusive value="5"/>
                        </xs:restriction>
                        </xs:simpleType>
                      </xs:element>
                      <xs:element name = "date" type = "xs:string"/> 
                    </xs:sequence>
                  </xs:complexType>
                </xs:element>
              </xs:sequence>
            </xs:complexType>
        </xs:element>
     


        <xs:element name="student"  >
          <xs:complexType>
            <xs:sequence>
              <xs:element name="s1" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name = "name" type = "xs:string"/>
                    <xs:element name = "regno" type = "xs:integer"/>
                    <xs:element name = "class" type = "xs:string"/>
                    <xs:element name = "native" type = "xs:string"/>
                    <xs:element name = "date" type = "xs:string"/>
                    <xs:element name = "membership">
                      <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:enumeration value="yes"/>
                          <xs:enumeration value="no"/>
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                    <xs:element name = "college" type = "xs:string"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== lalimary/Lab-4/lab3.xml
<?xml version="1.0" encoding ="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="lab3.xsl"?>
<admin xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="lab3.xsd">
 <library>
 <b1>
  <name> harry potter: The philosophers stone</name>
  <author> Jk rowling</author>
  <price> 2000</price>
  <pages> 300</pages>
  <genre> Fantasy and adventure</genre>
  <publisher>Bloomsbury</publisher>
  <rating>5</rating>
  <date> 26-06-97 </date>
 </b1>

<b1>
  <name>A better india: A better world</name>
  <author> Narayana murthy</author>
  <price> 3000</price>
  <pages> 320</pages>
  <genre> Philosophy</genre>
  <publisher>India penguin</publisher>
  <rating>4.5</rating>
  <date> 21-04-2009 </date>
 </b1>
 
 <b1>
 <name> A tale of two cities</name>
  <author> Charles dickens</author>
  <price> 5000</price>
  <pages> 300</pages>
  <genre> love</genre>
  <publisher>Weekly serial</publisher>
  <rating>3</rating>
  <date> 11-1859 </date>
 </b1>
</library>

 <student>
 <s1>
  <name>Ranjana c</name>
  <regno>2247251</regno>
  <class>MCA</class>
  <native>Bellary</native>
  <date>12-12-2001</date>
  <membership>yes</membership>
  <college>christ</college>
</s1>

<s1>
  <name>Lalitha Mary F</name>
  <regno>2247248</regno>
  <class>MCA</class>
  <native>Chikballapur</native>
  <date>28-09-2001</date>
  <membership>yes</membership>
  <college>christ</college>
</s1>

<s1>
  <name>Prerana Udupa</name>
  <regno>2247250</regno>
  <class>MCA</class>
  <native>Mangalore</native>
  <date>4-05-2000</date>
  <membership>no</membership>
  <college>christ</college>
</s1>
</student>
</admin>
